In [1]:
import pandas as pd

In [2]:
df=pd.read_excel("product reviews.xlsx")

In [3]:
print(df.head())

                     REVIEW SENTIMENT
0  The product is excellent  Positive
1         Very poor quality  Negative
2       I love this product  Positive
3        Worst product ever  Negative

In [4]:
print(df.columns)

Index(['REVIEW', 'SENTIMENT'], dtype='object')

In [5]:
print(df.shape)

(4, 2)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   REVIEW     4 non-null      object
 1   SENTIMENT  4 non-null      object
dtypes: object(2)
memory usage: 196.0+ bytes

In [7]:
df.describe()

                          REVIEW SENTIMENT
count                          4         4
unique                         4         2
top     The product is excellent  Positive
freq                           1         2

In [9]:
df.isnull().sum()

REVIEW       0
SENTIMENT    0
dtype: int64

In [10]:
print(df.dtypes)

REVIEW       object
SENTIMENT    object
dtype: object

In [11]:
df.dtypes

REVIEW       object
SENTIMENT    object
dtype: object

In [12]:
print("Dataset loaded successfully!")
print("Rows:",df.shape[0])
print("Columns:",df.shape[1])

Dataset loaded successfully!
Rows: 4
Columns: 2

In [13]:
df.head()

                     REVIEW SENTIMENT
0  The product is excellent  Positive
1         Very poor quality  Negative
2       I love this product  Positive
3        Worst product ever  Negative

In [14]:
df.tail()

                     REVIEW SENTIMENT
0  The product is excellent  Positive
1         Very poor quality  Negative
2       I love this product  Positive
3        Worst product ever  Negative

In [20]:
print("Missings Values:")
print(df.isnull().sum())

Missings Values:
REVIEW       0
SENTIMENT    0
dtype: int64

In [21]:
print("Duplicates rows:",df.duplicated().sum())

Duplicates rows: 0

In [22]:
print(df.dtypes)

REVIEW       object
SENTIMENT    object
dtype: object

In [25]:
print("Numerical columns:")
print(df.select_dtypes(include="number").columns.tolist())

Numerical columns:
[]

In [26]:
df=df.drop_duplicates()

In [28]:
print("Duplicates after cleaning:",df.duplicated().sum())

Duplicates after cleaning: 0

In [29]:
for column in df.columns:
    if df[column].dtype == "object":
        df[column] = df[column].fillna(df[column].mode()[0])
    else:
        df[column] = df[column].fillna(df[column].median())

In [30]:
print("Final Missing Values:")
print(df.isnull().sum())
print("Final Shape:", df.shape)

Final Missing Values:
REVIEW       0
SENTIMENT    0
dtype: int64
Final Shape: (4, 2)

In [31]:
df.to_excel("cleaned_product_reviews.xlsx", index=False)